---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: bitbucket-server-binding
spec:
  params:
    - name: gitrevision
      value: $(body.changes[0].ref.displayId)
    - name: gitrepositoryurl
      value: $(body.repository.links.clone[0].href)
